// Content for "Manifest the Money" — money mindset + method, MK Parrish voice.
export const manifestingMoney = {
  slug: "manifest-the-money",
  titleLead: "Manifest the",
  titleRest: "Money",
  subtitle: "The grounded guide to manifesting money — where mindset ends, math begins, and how to close the gap between the number you want and the number you'll actually say out loud.",
  price: "$24",
  blocks: [
    { h2: "Start Here" },
    "Manifesting money has a branding problem. It gets sold as a way to think your way to a windfall — visualize the check, feel the abundance, wait by the mailbox. That version does not work, and deep down you know it, which is probably why you're skeptical enough to want a book that's honest about it.",
    "Here's the honest version. Manifesting money is the practice of removing the mental blocks that keep you from *earning, asking for, pricing,* and *keeping* it — and then doing the concrete things a wealthier version of you would do. The mindset is real and it matters. But it matters because of the behavior it unlocks, not because the universe runs a payment processor.",
    "This book has two halves, and you need both. The first is the money mindset — the beliefs quietly capping what you allow yourself to charge, ask for, and receive. The second is the money math — the specific, unglamorous moves that turn a raised ceiling into an actual number in an actual account. Skip the mindset and you'll sabotage the math. Skip the math and you'll have great energy and an empty bank.",
    { quote: "Money doesn't respond to how badly you want it. It responds to what you'll ask for, what you'll charge, and what you'll do the day after you decide." },
    "Let's raise the ceiling and then go get the number.",
    "---",

    { h2: "The Number You Only Whisper" },
    "Say the amount you actually want to earn this year. Out loud. Not the reasonable one — the real one.",
    "Watch your body. If your voice dropped, if you laughed, if you rushed past it, you just found your money ceiling. It is not set by the market. It is set by the highest number you can say without flinching, because a number you're embarrassed by is a number you'll unconsciously price and pitch beneath.",
    "This is the whole hinge of manifesting money. Most people are not blocked by a lack of opportunity. They are blocked by a private cap — a figure above which some old voice says *who do you think you are.* We are going to find that cap, name it, and start moving it upward on purpose.",
    { h3: "Exercise: find your ceiling" },
    { ol: [
      "Write increasing income figures until one makes you tense: it should feel fine, fine, fine — then suddenly ridiculous.",
      "The number where the tension starts is roughly your current ceiling.",
      "Ask: whose voice says that number is too much? Where did you first hear it?",
      "Write the counter-truth in your own words. Say the higher number again. Then again tomorrow.",
    ] },
    "---",

    { h2: "The Money Stories You Inherited" },
    "Nobody arrives at money as a blank slate. You inherited a script — from family, culture, religion, the exact amount of money that was or wasn't around when you were small. Most of it runs silently, and most of it caps you.",
    "You cannot delete these stories, but you can drag them into the light, where they lose most of their power. Watch for the classics: money is dirty or corrupting; wanting more is greedy; charging full price is taking advantage; there's only so much to go around; people like us don't get to have that. Each one, unexamined, becomes a pricing decision.",
    { h3: "Common blocks and their rewrites" },
    { table: { head: ["The inherited story", "The rewrite"], rows: [
      ["Wanting more is greedy", "Wanting more capacity to help, pay people, and choose freely is responsible"],
      ["Charging full price is taking advantage", "A fair price for real value is the honest transaction; discounting to be liked is the dishonest one"],
      ["There's only so much to go around", "Value is created, not divided; my earning does not empty someone else's account"],
      ["People like us don't get to have that", "That was a description of a past circumstance, not a law about my future"],
    ] } },
    { h3: "Exercise: name three, rewrite three" },
    "Write the three money beliefs you absorbed before you were old enough to choose them. For each, write the truer sentence you'd tell a friend. Read the rewrites out loud. This is not affirmation fluff — it's editing the assumptions your pricing runs on.",
    "---",

    { h2: "Where Mindset Ends and Math Begins" },
    "Here's where this book parts ways with the vision-board version. A raised ceiling is necessary and not sufficient. Once you'll allow yourself to want and charge more, you have to build the machine that delivers it. Belief without a plan is a nicer kind of stuck.",
    "The money math is simple and most people avoid it because it's specific, and specific is where you can no longer hide. Your income is a product of three levers: how many people you reach, what fraction of them buy, and what each one pays. Manifesting money means deliberately moving at least one of these — and the fastest one to move is almost always price.",
    { h3: "The three levers" },
    { ul: [
      "**Reach** — how many of the right people encounter your offer. Grows slowly; compounds.",
      "**Conversion** — what fraction say yes. Improves with clearer positioning and proof.",
      "**Price** — what each yes is worth. The fastest lever, and the one your mindset most directly caps.",
    ] },
    { h3: "Exercise: the reverse-engineered number" },
    { ol: [
      "Write your real annual number.",
      "Divide by twelve for the monthly target.",
      "Divide by your current price for the number of yeses required.",
      "Now raise the price twenty percent and redo the math. Notice how many fewer yeses you need. The ceiling you moved earlier just did real work.",
    ] },
    "---",

    { h2: "Pricing Is a Manifestation" },
    "Nowhere does your money ceiling show up more plainly than in your prices. Under-pricing is rarely a math mistake; it's a self-worth statement wearing a discount. And here is the part people miss: your price is not just what you earn — it's a signal to the buyer about what you're worth, and they read it before they read anything else.",
    "Raising your price does three things at once. It increases what each yes is worth, it filters out the buyers who were going to be the most work for the least money, and — this is the manifesting part — it forces you to become the person who can say the higher number and hold the silence after it. That person earns more automatically, because they stop leaking money at every negotiation.",
    { h3: "The silence drill" },
    "Practice saying your price and then saying nothing. No justifying, no 'but I'm flexible,' no nervous discount before they've even reacted. The silence after the number is where the money is made or given away. Rehearse it until it's comfortable — out loud, to a mirror, to a friend.",
    { quote: "Your price is the first thing a buyer learns about how you value your own work. Lower it out of fear and they believe you." },
    "---",

    { h2: "Receiving (and Keeping)" },
    "Manifesting money isn't only about earning more. It's about being able to *receive* it without flinching and *keep* it without leaking. Plenty of people raise the ceiling, earn the number — and then unconsciously spend, discount, or over-give it all back, because at some level they don't believe they're allowed to hold it.",
    "Receiving well is a skill. It looks like taking the compliment, accepting the referral, letting someone pay full price without an apology tour, and not immediately giving the raise back to the world to prove you're still humble. Keeping well is a system: knowing your numbers, paying yourself first, and treating profit as a deliberate decision rather than whatever happens to be left.",
    { h3: "Exercise: the receiving audit" },
    { ol: [
      "Where do you deflect money — discounts offered before they're asked for, free work that was meant to be paid, prices softened mid-sentence?",
      "Where does money leak once it arrives — untracked spending, no profit set aside, giving it away to feel okay about having it?",
      "Pick one deflection and one leak. Close each this month.",
    ] },
    "---",

    { h2: "The Scarcity Loop" },
    "Scarcity is not a bank balance. It's a mode of thinking, and it can run just as loudly in someone with money as in someone without. Understanding the loop is essential, because scarcity thinking sabotages the exact behaviors that create wealth.",
    "Here's how the loop runs. You feel there isn't enough. That feeling narrows your focus to the immediate shortfall, which makes you play small — take the safe low-paying gig, discount to close fast, cling to a bad client because losing them feels catastrophic. Playing small produces small results, which confirms the original feeling that there isn't enough, which tightens the loop. Scarcity is self-fulfilling. It literally makes you make the decisions that keep you scarce.",
    "Abundance thinking is not delusion or 'good vibes.' It's the practical recognition that you can create value, that opportunities are not a fixed pie, and that one lost client or deal is a data point, not a disaster. From that steadier place you make better decisions — you hold your price, you walk from bad-fit work, you invest instead of only defending. The mindset isn't magic. It's the difference between decisions made from fear and decisions made from clarity, and over years those decisions are the whole story.",
    { h3: "Breaking the loop" },
    { ul: [
      "Widen the time horizon: 'this month is tight' is survivable when you're building a decade.",
      "Widen the options: a full pipeline makes any single no a non-event.",
      "Separate the fact from the feeling: 'I have $X' is a fact; 'there's never enough' is a story running on top of it.",
      "Make the decision you'd make if you weren't afraid — then check whether fear was actually the only objection.",
    ] },
    { quote: "Scarcity makes you take the deal that keeps you scarce. The first raise you have to give yourself is a raise in how you think." },
    "---",

    { h2: "Wealth Is Boring" },
    "The manifesting fantasy sells the windfall — the viral launch, the surprise check, the overnight change. Actual wealth, for almost everyone who builds it, is boring. It's the accumulated result of unremarkable habits repeated for an unremarkable long time.",
    "Earn a bit more than you spend. Widen the gap deliberately. Move the difference somewhere it grows before you can fritter it. Do that consistently and the outcome is, eventually, dramatic — but the process that got you there would put a documentary crew to sleep. The people who stay wealthy are rarely the ones who had one enormous moment. They're the ones who made the boring deposit, month after month, while everyone else waited for lightning.",
    "This matters for manifesting because the fantasy of the windfall keeps you from the boring machine that actually works. You skip the unglamorous system while you wait for the exciting event. Manifest the boring machine instead: the repeatable offer, the steady pipeline, the automatic savings, the price that goes up a little each year. Boring compounds. Exciting usually just spends.",
    { h3: "The boring machine" },
    { ol: [
      "A repeatable offer you can sell again and again without reinventing it.",
      "A steady source of the right leads so revenue doesn't depend on luck.",
      "A fixed percentage moved to savings/investment the day money lands.",
      "A price that rises deliberately over time as your proof accumulates.",
    ] },
    "---",

    { h2: "Charge the Value, Not the Hours" },
    "One of the fastest ways to raise your money ceiling is to stop selling your time and start selling the outcome. Time-based pricing caps you at the number of hours in a day and quietly tells the buyer your work is a commodity measured by the clock. Value-based pricing anchors the price to what the result is worth to them.",
    "Consider the difference. 'My rate is $100 an hour, and this will take about ten hours' invites the buyer to negotiate the hours down and to see you as interchangeable labor. 'This engagement gets you a website that converts the traffic you're already paying for — the investment is $6,000' anchors to the result and the return. Same work. Wildly different price ceiling, and a completely different conversation.",
    "This is a mindset shift before it's a pricing tactic. You have to believe the outcome is worth the number, which loops right back to the ceiling work from the opening chapters. When you undercharge, you're usually not pricing the hours too low — you're valuing the transformation too low, because some old story told you it wasn't worth much. Reprice the transformation and the number takes care of itself.",
    { h3: "Exercise: reprice one offer to the value" },
    { ol: [
      "Take one offer you currently price by time or by habit.",
      "Write down what the result is actually worth to the buyer — money made, money saved, time returned, risk removed, stress ended.",
      "Set a price that reflects a fair share of that value, not the hours you'll spend.",
      "Rewrite how you describe it: lead with the outcome, mention the price once, plainly.",
    ] },
    "---",

    { h2: "The Money Date" },
    "You cannot manifest what you refuse to look at, and most people avoid their numbers the way they avoid a scary email — hoping it resolves itself if ignored long enough. It never does. So we install a habit: a weekly money date.",
    "Once a week, for fifteen minutes, you sit down and look. What came in, what went out, what's owed to you, what you owe, and whether you're on track toward your number. That's it. No spreadsheet mastery required. The magic isn't in the sophistication; it's in the consistency of attention. Money grows where attention goes, not because of mysticism, but because you can only steer what you're actually watching.",
    "The money date also dissolves financial anxiety, which is usually worse in the dark. The dread of not-knowing is heavier than almost any number you'll actually find. Founders who avoid their finances live with a low, constant hum of fear; founders who look weekly trade that hum for clarity, even when the clarity is 'we need more sales this month.' Clarity you can act on. A vague hum just erodes you.",
    { h3: "Your weekly money date" },
    { ul: [
      "Money in this week vs. your weekly target.",
      "Money out — anything surprising or worth cutting.",
      "Outstanding invoices — who owes you, and is it time to follow up?",
      "One number that's trending the wrong way, and one small action to correct it.",
    ] },
    { quote: "The scariest thing about money is almost never the number. It's not looking. Look weekly and most of the fear simply leaves." },
    "---",

    { h2: "Invest in the Earner" },
    "Manifesting money eventually requires spending some, and where you spend it is a statement about what you believe. The highest-return investment available to most people is not a stock or a side hustle. It's the person doing the earning — you.",
    "Skills, positioning, tools that buy back your time, help that removes your bottleneck, rooms full of people playing a bigger game than you are: these are investments in your capacity to earn, and capacity is the thing that compounds hardest. The founder who reinvests in becoming more valuable raises the ceiling on everything downstream. The one who hoards every dollar out of scarcity often stays exactly as capable — and therefore exactly as capped — as they were.",
    "This is not permission to buy every course and call it growth. It's a filter: does this spend make me meaningfully more valuable, buy back time I can sell for more, or remove the bottleneck holding the number down? If yes, it's an investment. If it's just anxiety-shopping for a shortcut, it's an expense in disguise. Learn the difference and put real money behind the earner.",
    { h3: "Exercise: one investment in your earning power" },
    "Name the single skill, tool, or support that would most raise your capacity to earn this year. Price it. Then ask whether the story stopping you from buying it is a real budget constraint or the same old ceiling telling you you're not worth the investment.",
    "---",

    { h2: "The Emotional Life of Money" },
    "Money is never just numbers. It's loaded with feeling — safety, freedom, worth, guilt, shame, power, love. Two people with identical bank balances can live in completely different emotional realities, one anxious and grasping, the other calm and generous. The difference isn't the number. It's the relationship.",
    "Manifesting money without tending to that relationship is like pouring water into a cracked cup. You can earn more and still feel broke, because the feeling was never about the amount. Chronic money anxiety in someone objectively fine, compulsive over-giving, the inability to spend on yourself, the secret shame about what you do or don't have — these are relationship problems, not math problems, and no windfall fixes them. Plenty of people have proven that by winning money and feeling exactly as scared six months later.",
    "So part of the work is emotional. Notice what money makes you feel and where you learned to feel it. Notice the moments you use money to manage an emotion — spending to soothe, hoarding to feel safe, giving to feel worthy. You don't have to fix all of it. You just have to see it, because a relationship you can see is one you can slowly change, and a calmer relationship with money makes every practical decision in this book easier.",
    { h3: "Exercise: your money feelings" },
    { ol: [
      "Finish: 'When I think about money, I mostly feel ____.'",
      "Where did you first feel that? Whose relationship with money are you echoing?",
      "Name one way you use money to manage a feeling rather than to meet a need.",
      "Write the calmer relationship you want — and one small behavior that reflects it.",
    ] },
    "---",

    { h2: "Their Objection Is Usually Yours" },
    "When you start charging more, you'll brace for pushback. Here's the pattern almost nobody warns you about: the objection you're most afraid of hearing is usually the one you secretly hold yourself. You fear they'll say 'that's too expensive' because part of you believes it's too expensive.",
    "Buyers are remarkably good at reading your conviction. If you don't fully believe the price is fair, that doubt leaks into how you say the number — the flinch, the rushed justification, the discount offered before they've even reacted — and they price the doubt right back to you. The objection isn't really about their budget. It's a mirror reflecting your own uncertainty about whether you're worth it.",
    "This is why the ceiling work and the pricing work are the same work. When you genuinely believe the value is there — because you've done the reframing, seen the results, and reverse-engineered the worth — you say the number cleanly and hold the silence, and a surprising share of the objections simply never arrive. The rest, from people for whom it's genuinely not a fit, you can hear without collapsing, because your worth was never on the table in the first place.",
    { quote: "The price objection you dread most is the one you haven't resolved in yourself. Convince yourself first; the market is downstream of your conviction." },
    { h3: "Exercise: resolve your own objection" },
    "Write the price objection you're most afraid to hear. Then write the honest case for why the price is fair — the outcome, the results, the value delivered. If you can't make that case convincingly to yourself, that's the work to do before the next quote, not the market's problem to solve for you.",
    "---",

    { h2: "Debt, Fear, and the Fresh Start" },
    "For a lot of people, money isn't a blank field to grow — it's a hole to climb out of first. Debt carries its own emotional weight: shame, dread, the sense of being permanently behind. If that's you, manifesting money starts with turning the fear into a plan, because fear keeps you from looking, and not looking is what lets debt quietly run your life.",
    "The move is the same one from the money date, applied with more compassion: look at the whole number, awful as it feels, because the not-knowing is heavier than the knowing. Write down exactly what's owed, to whom, at what cost. A defined number is a problem you can attack; a vague dread is a problem that attacks you. Most people find the real total, while serious, is more finite and more workable than the monster they'd been imagining in the dark.",
    "Then it becomes a system, not a source of self-hatred. A steady amount toward the debt, protected like any other habit, chips it down through the same compounding that builds wealth — just in reverse and in your favor. And crucially: you're allowed a fresh start. The financial story so far is not a verdict on your future. Plenty of people who now have real stability once stood exactly where you are, looking at a number that felt impossible, and simply began.",
    { h3: "The debt reset" },
    { ul: [
      "Write the full picture: every balance, rate, and minimum. Look at all of it once.",
      "Pick a strategy you'll actually stick to (smallest balance first for momentum, or highest rate first for math).",
      "Automate a fixed payment as a non-negotiable habit, however small.",
      "Drop the shame. It doesn't pay down a cent, and it keeps you from looking.",
    ] },
    "---",

    { h2: "Generosity Without Self-Erasure" },
    "Many kind, giving people have a specific money wound: they can receive nothing and give everything, and they call it virtue. It isn't, entirely. Over-giving that leaves you depleted, resentful, or broke isn't generosity — it's self-erasure with a halo on it, and it quietly keeps you from ever building the stability that would let you give from real abundance.",
    "True generosity requires having something to give. The instruction from the safety demonstration applies here: secure your own oxygen mask first. Building your own financial stability is not selfish; it's what makes sustained generosity possible. The person who tends their own resources can give freely for decades. The person who gives themselves empty burns out and has nothing left for anyone, themselves included.",
    "So let yourself receive. Take full price without an apology. Accept the referral, the raise, the gift, the compliment. Build the reserve. And then give — deliberately, from surplus, in a way that doesn't require you to disappear. Manifesting money and being a genuinely generous person are not in tension. The most generous people, sustained over a life, are usually the ones who first allowed themselves to have.",
    { quote: "Giving until you're empty isn't generosity — it's self-erasure. Fill the cup first; then pour from the overflow for the rest of your life." },
    "---",

    { h2: "The Wealth Identity" },
    "Everything in this book converges on one thing: the identity of a person who earns, holds, and grows money with ease. Outcomes follow identity, and a shaky money identity will sabotage even a great strategy, quietly, at every decision point.",
    "A person with a healthy wealth identity does specific, learnable things. They know their numbers. They charge fairly and hold the price. They receive without apology and invest in their own capacity. They think in decades, not weeks. They treat money as a tool and a responsibility rather than a verdict on their worth. None of this requires a trust fund or a personality transplant — it requires practicing the behaviors until they feel like yours, at which point the identity is simply true.",
    "This is the manifesting part, correctly understood. You don't visualize the money into existence. You become — through repeated, slightly-bolder behavior and repeated evidence — the kind of person for whom this level of money is normal. And for that person, the number you're chasing today isn't a miracle. It's a Tuesday.",
    { h3: "Exercise: step into the identity" },
    { ol: [
      "Write: 'A person who is at ease with money would ____.' Fill it in for pricing, spending, saving, and receiving.",
      "Choose the one behavior on that list you resist most.",
      "Do it this week, and log it. Identity is built from evidence, and you're collecting it.",
      "Repeat with the next behavior until the wealth identity stops being aspirational and starts being ordinary.",
    ] },
    "---",

    { h2: "The 30-Day Money Reset" },
    "The whole book as a plan. Half mindset, half math, because you need both.",
    { h3: "Week One — Raise the ceiling" },
    { ol: [
      "Find your ceiling; say the higher number daily until it stops flinching.",
      "Name three inherited money stories; write the rewrites.",
      "Read the rewrites out loud each morning.",
    ] },
    { h3: "Week Two — Do the math" },
    { ol: [
      "Reverse-engineer your number into monthly yeses.",
      "Redo it with a twenty-percent higher price.",
      "Choose the one lever — reach, conversion, or price — you'll move first.",
    ] },
    { h3: "Week Three — Charge it" },
    { ol: [
      "Raise the price of one offer to match the new ceiling.",
      "Practice the silence drill daily.",
      "Quote the new price to the next prospect without softening it.",
    ] },
    { h3: "Week Four — Receive and keep" },
    { ol: [
      "Run the receiving audit; close one deflection and one leak.",
      "Set up 'pay yourself first' — move a fixed percentage the day money lands.",
      "Review: what did you allow yourself to earn, ask for, and keep that you wouldn't have thirty days ago?",
    ] },
    "---",

    { h2: "Comparison Is a Money Leak" },
    "There's a specific tax most people pay without noticing, and it quietly drains both their money and their peace: comparison. In an age where everyone broadcasts their highlight reel, it's nearly impossible not to measure your finances against a feed full of other people's curated wins.",
    "Comparison distorts your money decisions in expensive ways. It makes you spend to match a lifestyle that may itself be fake or debt-funded. It makes you feel behind and therefore rush — into the bad deal, the discount, the desperate pitch — which is precisely how scarcity thinking gets its grip. And it makes you devalue real progress because someone else appears further ahead, even though you have no idea what their actual balance sheet, stress level, or starting point looks like.",
    "The antidote is to run your own race against your own numbers. The only honest comparison is you versus you: are you further along than last year, closer to your number, calmer with money than you were? That's a comparison you can act on. Someone else's highlight reel is not data; it's a distraction dressed as motivation. Close the app, open your own ledger, and measure the only thing that's actually yours to change.",
    { quote: "Comparison spends money you don't have to impress people you don't know. Run your own race; it's the only one you can actually win." },
    "---",

    { h2: "The Multiple-Streams Myth" },
    "'Multiple streams of income' gets repeated like scripture in the manifesting-money world, usually by people selling you the course on how to build them. There's truth in it and there's a trap, and telling them apart will save you years.",
    "The truth: relying on a single source of income is fragile, and building additional streams can create real security and growth. The trap: most people try to build several streams at once, before any single one is stable, and end up with a handful of leaky trickles instead of one strong river. Five half-built income sources that each earn a little is not diversification — it's dilution, and it's exhausting.",
    "The grounded sequence is boring and it works: make one stream genuinely strong first. Get one offer, one skill, one source producing reliable money before you split your attention. Then, from that stable base, add a second stream that compounds with the first — ideally one that uses the same audience, skill, or asset rather than a brand-new hustle. Depth before breadth. A single deep, reliable stream beats a scattered delta of shallow ones every time, and it's the only foundation solid enough to build the next stream on.",
    { h3: "Exercise: strengthen before you multiply" },
    { ul: [
      "Name your primary income stream. Is it genuinely stable and optimized, or just familiar?",
      "List everything you'd improve about it before starting anything new.",
      "Only once it's strong, choose a second stream that reuses your existing audience, skill, or asset.",
    ] },
    "---",

    { h2: "Visualize the Wealthy You — Correctly" },
    "Visualization is the most caricatured tool in manifesting — the person staring at a picture of a yacht, willing it closer. Done that way, it's useless. But there's a version of visualization that actually works, and it has nothing to do with summoning objects. It's about rehearsing an identity until your behavior catches up to it.",
    "Effective visualization is not picturing the money. It's picturing the person who has it — and specifically, how that person behaves. Don't imagine the bank balance; imagine yourself quoting your real price without flinching, following up without apology, saying no to the wrong-fit client with ease, looking at your numbers calmly on a Friday. When you rehearse the behaviors of the wealthy version of you, you make those behaviors more familiar and therefore more likely. The mind treats vivid rehearsal a little like practice, and the point of practice is the doing, not the wanting.",
    "This is why athletes rehearse the race, not the medal. The medal is downstream; the performance is what visualization can actually improve. Apply the same logic to money. Spend two minutes imagining yourself moving through a specific money situation — a pricing conversation, a negotiation, a decision to invest in yourself — as the person you're becoming would move through it. Then, when the real moment arrives, you've been there before. The visualization did its job: not by attracting the money, but by rehearsing you into the person who earns it.",
    { h3: "Exercise: rehearse the behavior" },
    { ol: [
      "Pick one money situation you find hard (quoting a price, following up, saying no).",
      "Spend two minutes vividly rehearsing yourself handling it with ease — the words, the calm, the silence after the number.",
      "Do it daily until the real version feels familiar instead of frightening.",
    ] },
    { quote: "Don't visualize the money. Visualize the person who charges what they're worth and holds the silence. Become her in rehearsal; the money follows the behavior." },
    "---",

    { h2: "Define Your Enough" },
    "Here is a question the manifesting world almost never asks, because it doesn't sell courses: how much is enough? Not the ceiling you're raising, not the ambitious number — the amount at which you'd actually feel free, at ease, done proving. Most people chase 'more' forever precisely because they never defined enough, and a target you never name is a target you can never hit.",
    "Without an 'enough' number, more money doesn't buy peace; it just resets the baseline. This is lifestyle creep — earnings rise, spending rises to match, and the feeling of scarcity survives every raise intact. People who swore they'd feel secure at a certain income arrive there and immediately need the next one, because the goalpost was never a number, it was a feeling, and the feeling followed them up the ladder. Manifesting money without defining enough is how you end up wealthy and still anxious, which is a real and common tragedy.",
    "So define it. What income would cover the life you actually want — the home, the freedom, the generosity, the security — with margin to spare? That's your enough. Naming it does two powerful things at once. It gives your manifesting a real finish line to aim at, which makes the effort feel purposeful instead of infinite. And it protects you from the trap of sacrificing your whole life to a number that keeps receding. You may well earn past your enough — that's fine, and it funds bigger generosity and bigger bets. But you'll be doing it from choice and abundance, not from a fear that no amount ever silences.",
    { h3: "Exercise: name your enough" },
    { ol: [
      "Write the annual income that would fund the life you genuinely want, with margin.",
      "Break down what that number actually covers — housing, freedom, giving, security, joy.",
      "Notice the gap between 'enough' and 'as much as possible.' Which have you been chasing, and why?",
      "Let 'enough' be your first finish line. Anything past it is a choice, not a compulsion.",
    ] },
    { quote: "If you never define enough, no amount will ever feel like it. Name the number that means free — then chase it instead of chasing forever." },
    "---",

    { h2: "The One-Percent Money Habits" },
    "Manifesting money is not one heroic financial move. It's a handful of small habits repeated until they compound — the money version of everything in the micro-habits playbook. Individually they look trivial. Stacked over years, they're the difference between constant anxiety and quiet stability.",
    "Here are the small, boring habits that quietly build wealth. Notice that none of them require a windfall, a rich relative, or a viral moment. They require only consistency, which is available to almost everyone and practiced by almost no one.",
    { ul: [
      "Pay yourself first: the day money lands, move a fixed percentage to savings or investment before you can spend it.",
      "Look weekly: the fifteen-minute money date keeps you steering instead of drifting.",
      "Raise prices annually: a small, deliberate increase each year, in step with your growing proof.",
      "Invoice immediately and follow up promptly: most 'cash flow problems' are really 'I didn't ask' problems.",
      "Sleep on purchases over a set amount: a 24-hour rule kills most impulse leaks without any deprivation.",
      "Reinvest a slice into your earning power: skills and tools that raise the ceiling.",
    ] },
    "Pick one. Make it automatic. Add another only when the first is second nature. This is the compound curve applied to money — flat and unremarkable for a while, then suddenly a different financial life.",
    { h3: "Automate the good decisions" },
    "The single highest-leverage move is to remove yourself from the loop wherever you can. Automatic transfers to savings the day you're paid, automatic bill payment, automatic investment — each one is a good decision you make once that then keeps making itself, immune to the mood you're in that week. Willpower is unreliable; automation is not. Set up the machine so that doing the right thing with money requires no discipline at all, because the discipline is built into the system.",
    { quote: "Wealth is not built in the big, dramatic money moments. It's built in the small automatic ones you set up once and then forget." },
    "---",

    { h2: "Money Myths, Debunked" },
    "Before the worksheets, let's clear the most common myths that keep people stuck — the beliefs that sound wise and quietly cap you.",
    { ul: [
      "**'Money is the root of all evil.'** A misquote. The original line warns about the *love* of money over everything else. Money itself is neutral — a tool that amplifies whoever holds it. In good hands it does enormous good.",
      "**'You have to spend money to make money.'** Sometimes, strategically — but this myth funds a lot of anxious over-spending. Spend on what raises your capacity to earn; not on the appearance of a business.",
      "**'Wanting more makes you greedy.'** Wanting more capacity to help, pay people, give, and choose freely is responsible, not greedy. Greed is hoarding at others' expense; ambition is creating value and being paid fairly for it.",
      "**'Rich people are lucky / born into it.'** Some are. Many built it through exactly the unglamorous habits in this book. Luck helps; consistency compounds.",
      "**'I'm just not good with money.'** This is a story, not a diagnosis. Being good with money is a set of learnable habits — looking weekly, saving automatically, charging fairly. You can start being 'good with money' this week.",
      "**'Talking about money is tacky.'** Silence about money mostly benefits the people who'd rather you not know your worth. Clarity — about prices, salaries, and numbers — is how you stop leaving money on the table.",
    ] },
    "Notice how many of these you absorbed without ever choosing them. Each one, unexamined, becomes a pricing decision or a permission you refuse yourself. Debunk them on paper and you loosen their grip on your ceiling.",
    "---",

    { h2: "Field Notes & Worksheets" },
    "The system as fill-in pages. Half mindset, half math. Work them by hand.",
    { h3: "1. My ceiling" },
    "The highest number I can say without flinching today: ________. The number where the tension starts: ________. The voice that says it's 'too much' belongs to: ____________.",
    { h3: "2. My money stories (name three, rewrite three)" },
    "Story: ____________ → Rewrite: ____________.",
    "Story: ____________ → Rewrite: ____________.",
    "Story: ____________ → Rewrite: ____________.",
    { h3: "3. The math" },
    "Real annual number: ________. Monthly (÷12): ________. Yeses needed at current price: ________. Yeses needed at +20% price: ________.",
    { h3: "4. Repricing" },
    "The offer I'll reprice: ____________. Old price: ________. New price (to the value): ________. I will say it and then say nothing.",
    { h3: "5. My weekly money date" },
    "Day and time: ____________. In vs. target: ________. One number trending wrong: ________. One corrective action: ____________.",
    { h3: "6. Receiving audit" },
    "One place I deflect money: ____________ → I'll stop by ____________. One leak once it arrives: ____________ → I'll close it by ____________.",
    "---",

    { h2: "The Close" },
    "Money does not respond to how badly you want it. It responds to what you'll ask for, what you'll charge, what you'll do the day after you decide, and what you'll let yourself keep. Raise the ceiling so you'll allow the number. Do the math so you'll actually reach it. Charge like you believe it, receive like you deserve it, and keep it like it's yours — because it is.",
    "That's manifesting money without the magical thinking. The mindset opens the door. The math walks you through it.",
    { quote: "First you decide you're allowed to have it. Then you go do the specific, unglamorous things that people who have it do. Both halves. Every time." },
    "Rewrite your story — and your ledger. ♡",
    "— MK",
  ],
};
